class Appliance:
    def __init__(self):
        self.appliance_list = ("Air conditiontioner",
                               "Air ioniser", 
                               "Evaporator Cooler", 
                               "Air purifier",
                               "Appliance plug",
                               "Aroma lamp",
                               "Attic fan",
                               "Bachelor griller",
                               "Back boiler",
                               "Beverage opener",
                               "Blender",
                               "Box mangle",
                               "Can opener",
                               "Ceiling fan",
                               "Central vacuum cleaner",
                               "Clothes dryer",
                               "Clothes iron",
                               "Cold-pressed juicer",
                               "Combo washer dryer",
                               "Dish draining closet",
                               "Dishwasher",
                               "Domestic robot",
                               "Drawer dishwasher",
                               "Electric water boiler",
                               "Exhaust hood",
                               "Fan heater",
                               "Flame supervision device",
                               "Forced-air",
                               "Futon dryer",
                               "Garbage disposal unit",
                               "Gas appliance",
                               "Go-to-bed matchbox",
                               "Hair dryer",
                               "Hair iron",
                               "Hob(hearth)",
                               "Home server",
                               "Humidifier",
                               "HVAC",
                               "Icebox",
                               "Jukebox",
                               "Kimchi refrigerator",
                               "Light fixture",
                               "Light",
                               "Mangle(machine)",
                               "Micathermic heater",
                               "Microwave oven",
                               "Mousetrap",
                               "Oil heater",
                               "Oven",
                               "Patio heater",
                               "Paper shredder",
                               "Quacking toy",
                               "Radiator(heating)",
                                "Refrigerator",
                                "Sewing machine",
                                "Space heater",
                                "Steam mop",
                                "Stove",
                                "Sump pump",
                                "Television",
                                "Tie press",
                                "Toaster and toaster ovens",
                                "Trouser press",
                                "Underwear cleaner",
                                "Vacuum cleaner",
                                "Washing machine",
                                "Water cooker",
                                "Water purifier",
                                "Water heater",
                                "Window fan",
                                "Washing machine",
                                "Waffle iron",
                                "Xerox machine",
                                "X-Acto knife",
                                "Yagi aerial",
                                "Zither(Electric)",
    )


    


